#!/bin/bash

echo ""
echo ""
echo "Program ekstrahujący \"ładny\" tekst w języku polskim ze strony internetowej."
echo "Przez \"ładny\" tekst rozumiemy kompletne zdania w języku polskim bez żadnych dodatkowych elementów (linki, etc.),"
echo "w ustalonym jednolitym kodowaniu, podzielony na zdania (1 zdanie w 1 linii)."
echo "Struktura wejściowej strony internetowej nie jest w żaden sposób określona,"
echo "Program powinien radzić sobie z dowolnymi stronami."

echo ""
echo "ENTER -> dalej"
read enter

echo 'Do prawidłowego działania wymagana jest biblioteka Nokogiri, zainstalować?[t/n]'

read var
if [ $var == 't' ]
then
	echo 'Instaluje...'
	sudo gem install nokogiri
fi

echo ""
echo ""
echo "Zadanie wykonał Marcin Łazur 396365"
echo ""
echo ""

echo "Instrukcja ogólna:"
echo "uruchonienie => ./app.rb ARG1"
echo "Gdzie ARG1 - adres strony internetowej z której ma być ekstahiwany tekst"
echo "W tym demie odpalony zostanie program kilka razy dla różnych stron"

echo ""
echo "ENTER -> dalej"
read enter

echo "Przykład 1: Strona Wikipedii - Malowany Człowiek"
echo "ENTER -> dalej"
read enter
ruby app.rb https://pl.wikipedia.org/wiki/Malowany_cz%C5%82owiek

echo ""
echo "ENTER -> dalej"
read enter

echo "Przykład 2: Artykuł ze strony cdaction.pl"
echo "ENTER -> dalej"
read enter
ruby app.rb https://www.cdaction.pl/news-52437/dragon-ball-fighterz-miazdzy-konkurencje-na-steamie.html

echo ""
echo "ENTER -> dalej"
read enter

echo "Przykład 3: niebezpiecznik.pl - artykuł o meltdown"
echo "ENTER -> dalej"
read enter
ruby app.rb https://niebezpiecznik.pl/post/szczegoly-techniczne-dziury-w-procesorach-intela-amd-i-arm-czyli-ataki-meltdown-i-spectre/
